In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('diabetes_prediction_dataset.csv')
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [3]:
df.shape

(100000, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  object 
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  object 
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB


In [5]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [6]:
df.duplicated().sum()
df[df.duplicated()]
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(96146, 9)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96146 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               96146 non-null  object 
 1   age                  96146 non-null  float64
 2   hypertension         96146 non-null  int64  
 3   heart_disease        96146 non-null  int64  
 4   smoking_history      96146 non-null  object 
 5   bmi                  96146 non-null  float64
 6   HbA1c_level          96146 non-null  float64
 7   blood_glucose_level  96146 non-null  int64  
 8   diabetes             96146 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 7.3+ MB


In [9]:
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [10]:
df['diabetes'].unique()

array([0, 1], dtype=int64)

In [11]:
df['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [12]:
# df.drop(df[df['gender']=='Other'],axis=1,inplace=True)
df.shape

(96146, 9)

In [13]:
df=df[df['gender']!='Other']
df.shape

(96128, 9)

In [14]:
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [15]:
df['age'].unique()

array([80.  , 54.  , 28.  , 36.  , 76.  , 20.  , 44.  , 79.  , 42.  ,
       32.  , 53.  , 78.  , 67.  , 15.  , 37.  , 40.  ,  5.  , 69.  ,
       72.  ,  4.  , 30.  , 45.  , 43.  , 50.  , 41.  , 26.  , 34.  ,
       73.  , 77.  , 66.  , 29.  , 60.  , 38.  ,  3.  , 57.  , 74.  ,
       19.  , 46.  , 21.  , 59.  , 27.  , 13.  , 56.  ,  2.  ,  7.  ,
       11.  ,  6.  , 55.  ,  9.  , 62.  , 47.  , 12.  , 68.  , 75.  ,
       22.  , 58.  , 18.  , 24.  , 17.  , 25.  ,  0.08, 33.  , 16.  ,
       61.  , 31.  ,  8.  , 49.  , 39.  , 65.  , 14.  , 70.  ,  0.56,
       48.  , 51.  , 71.  ,  0.88, 64.  , 63.  , 52.  ,  0.16, 10.  ,
       35.  , 23.  ,  0.64,  1.16,  1.64,  0.72,  1.88,  1.32,  0.8 ,
        1.24,  1.  ,  1.8 ,  0.48,  1.56,  1.08,  0.24,  1.4 ,  0.4 ,
        0.32,  1.72,  1.48])

In [16]:
df.describe()

age  hypertension  heart_disease           bmi   HbA1c_level  \
count  96128.000000  96128.000000   96128.000000  96128.000000  96128.000000   
mean      41.796617      0.077615       0.040810     27.321450      5.532633   
std       22.463329      0.267567       0.197851      6.767811      1.073225   
min        0.080000      0.000000       0.000000     10.010000      3.500000   
25%       24.000000      0.000000       0.000000     23.400000      4.800000   
50%       43.000000      0.000000       0.000000     27.320000      5.800000   
75%       59.000000      0.000000       0.000000     29.860000      6.200000   
max       80.000000      1.000000       1.000000     95.690000      9.000000   

       blood_glucose_level      diabetes  
count         96128.000000  96128.000000  
mean            138.218001      0.088237  
std              40.911190      0.283640  
min              80.000000      0.000000  
25%             100.000000      0.000000  
50%             140.000000      0.000000  
75%             159.000000      0.000000  
max             300.000000      1.000000

In [17]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [18]:
df['gender']=np.where(df['gender'].str.contains('Female'),0,1)

In [19]:
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0       0  80.0             0              1           never  25.19   
1       0  54.0             0              0         No Info  27.32   
2       1  28.0             0              0           never  27.32   
3       0  36.0             0              0         current  23.45   
4       1  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96128 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               96128 non-null  int32  
 1   age                  96128 non-null  float64
 2   hypertension         96128 non-null  int64  
 3   heart_disease        96128 non-null  int64  
 4   smoking_history      96128 non-null  object 
 5   bmi                  96128 non-null  float64
 6   HbA1c_level          96128 non-null  float64
 7   blood_glucose_level  96128 non-null  int64  
 8   diabetes             96128 non-null  int64  
dtypes: float64(3), int32(1), int64(4), object(1)
memory usage: 7.0+ MB


In [21]:
###NOw looking for ages
df['age'].unique()

array([80.  , 54.  , 28.  , 36.  , 76.  , 20.  , 44.  , 79.  , 42.  ,
       32.  , 53.  , 78.  , 67.  , 15.  , 37.  , 40.  ,  5.  , 69.  ,
       72.  ,  4.  , 30.  , 45.  , 43.  , 50.  , 41.  , 26.  , 34.  ,
       73.  , 77.  , 66.  , 29.  , 60.  , 38.  ,  3.  , 57.  , 74.  ,
       19.  , 46.  , 21.  , 59.  , 27.  , 13.  , 56.  ,  2.  ,  7.  ,
       11.  ,  6.  , 55.  ,  9.  , 62.  , 47.  , 12.  , 68.  , 75.  ,
       22.  , 58.  , 18.  , 24.  , 17.  , 25.  ,  0.08, 33.  , 16.  ,
       61.  , 31.  ,  8.  , 49.  , 39.  , 65.  , 14.  , 70.  ,  0.56,
       48.  , 51.  , 71.  ,  0.88, 64.  , 63.  , 52.  ,  0.16, 10.  ,
       35.  , 23.  ,  0.64,  1.16,  1.64,  0.72,  1.88,  1.32,  0.8 ,
        1.24,  1.  ,  1.8 ,  0.48,  1.56,  1.08,  0.24,  1.4 ,  0.4 ,
        0.32,  1.72,  1.48])

In [22]:
df=df[~df['age'].between(0,0.99)]

In [23]:
df.shape

(95218, 9)

In [24]:
df['age'].unique()

array([80.  , 54.  , 28.  , 36.  , 76.  , 20.  , 44.  , 79.  , 42.  ,
       32.  , 53.  , 78.  , 67.  , 15.  , 37.  , 40.  ,  5.  , 69.  ,
       72.  ,  4.  , 30.  , 45.  , 43.  , 50.  , 41.  , 26.  , 34.  ,
       73.  , 77.  , 66.  , 29.  , 60.  , 38.  ,  3.  , 57.  , 74.  ,
       19.  , 46.  , 21.  , 59.  , 27.  , 13.  , 56.  ,  2.  ,  7.  ,
       11.  ,  6.  , 55.  ,  9.  , 62.  , 47.  , 12.  , 68.  , 75.  ,
       22.  , 58.  , 18.  , 24.  , 17.  , 25.  , 33.  , 16.  , 61.  ,
       31.  ,  8.  , 49.  , 39.  , 65.  , 14.  , 70.  , 48.  , 51.  ,
       71.  , 64.  , 63.  , 52.  , 10.  , 35.  , 23.  ,  1.16,  1.64,
        1.88,  1.32,  1.24,  1.  ,  1.8 ,  1.56,  1.08,  1.4 ,  1.72,
        1.48])

In [25]:
encode=LabelEncoder()
encode.fit(df['smoking_history'])

LabelEncoder()

In [26]:
df['smoking_history']=encode.transform(df['smoking_history'])

In [27]:
df

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19   
1           0  54.0             0              0                0  27.32   
2           1  28.0             0              0                4  27.32   
3           0  36.0             0              0                1  23.45   
4           1  76.0             1              1                1  20.14   
...       ...   ...           ...            ...              ...    ...   
99994       0  36.0             0              0                0  24.60   
99996       0   2.0             0              0                0  17.37   
99997       1  66.0             0              0                3  27.83   
99998       0  24.0             0              0                4  35.42   
99999       0  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99994          4.8                  145         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[95218 rows x 9 columns]

In [28]:
df['smoking_history'].unique()

array([4, 0, 1, 3, 2, 5])

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95218 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               95218 non-null  int32  
 1   age                  95218 non-null  float64
 2   hypertension         95218 non-null  int64  
 3   heart_disease        95218 non-null  int64  
 4   smoking_history      95218 non-null  int32  
 5   bmi                  95218 non-null  float64
 6   HbA1c_level          95218 non-null  float64
 7   blood_glucose_level  95218 non-null  int64  
 8   diabetes             95218 non-null  int64  
dtypes: float64(3), int32(2), int64(4)
memory usage: 6.5 MB


In [30]:
df.describe()

gender           age  hypertension  heart_disease  \
count  95218.000000  95218.000000  95218.000000   95218.000000   
mean       0.414733     42.191027      0.078357       0.041200   
std        0.492678     22.203388      0.268734       0.198754   
min        0.000000      1.000000      0.000000       0.000000   
25%        0.000000     24.000000      0.000000       0.000000   
50%        0.000000     43.000000      0.000000       0.000000   
75%        1.000000     60.000000      0.000000       0.000000   
max        1.000000     80.000000      1.000000       1.000000   

       smoking_history           bmi   HbA1c_level  blood_glucose_level  \
count     95218.000000  95218.000000  95218.000000         95218.000000   
mean          2.250299     27.417477      5.534337           138.268426   
std           1.876222      6.717427      1.073849            40.968341   
min           0.000000     10.010000      3.500000            80.000000   
25%           0.000000     23.550000      4.800000           100.000000   
50%           3.000000     27.320000      5.800000           140.000000   
75%           4.000000     29.930000      6.200000           159.000000   
max           5.000000     95.690000      9.000000           300.000000   

          diabetes  
count  95218.00000  
mean       0.08908  
std        0.28486  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max        1.00000

In [32]:
df.corr()

gender       age  hypertension  heart_disease  \
gender               1.000000 -0.025345      0.014887       0.079367   
age                 -0.025345  1.000000      0.256476       0.238758   
hypertension         0.014887  0.256476      1.000000       0.119473   
heart_disease        0.079367  0.238758      0.119473       1.000000   
smoking_history     -0.078285  0.227579      0.085557       0.021660   
bmi                 -0.021313  0.327955      0.145839       0.059186   
HbA1c_level          0.020794  0.105945      0.081354       0.068112   
blood_glucose_level  0.018307  0.114294      0.084802       0.070836   
diabetes             0.038706  0.263867      0.195002       0.170201   

                     smoking_history       bmi  HbA1c_level  \
gender                     -0.078285 -0.021313     0.020794   
age                         0.227579  0.327955     0.105945   
hypertension                0.085557  0.145839     0.081354   
heart_disease               0.021660  0.059186     0.068112   
smoking_history             1.000000  0.171765     0.033954   
bmi                         0.171765  1.000000     0.083381   
HbA1c_level                 0.033954  0.083381     1.000000   
blood_glucose_level         0.037427  0.092202     0.173139   
diabetes                    0.085930  0.213226     0.407839   

                     blood_glucose_level  diabetes  
gender                          0.018307  0.038706  
age                             0.114294  0.263867  
hypertension                    0.084802  0.195002  
heart_disease                   0.070836  0.170201  
smoking_history                 0.037427  0.085930  
bmi                             0.092202  0.213226  
HbA1c_level                     0.173139  0.407839  
blood_glucose_level             1.000000  0.425607  
diabetes                        0.425607  1.000000

In [33]:
df.to_csv('Cleaned_data.csv',index=False)